"""Added new column

Revision ID: 649622e55f9a
Revises: 65154f0fdeec
Create Date: 2025-03-13 12:24:56.075766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649622e55f9a'
down_revision: Union[str, None] = '65154f0fdeec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('your_table_name', sa.Column('new_column_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('your_table_name', 'new_column_name')
    # ### end Alembic commands ###