"""Initial migration

Revision ID: 65154f0fdeec
Revises: 
Create Date: 2025-03-13 12:24:06.397069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65154f0fdeec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'your_table_name',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('column1', sa.String(length=255), nullable=False),
        sa.Column('column2', sa.String(length=255), nullable=True),
        # Add more columns as needed
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('your_table_name')
    # ### end Alembic commands ###